//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MultiUser
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminReg
    {
        public int Id { get; set; }
        public string AdName { get; set; }
        public string AdAddr { get; set; }
        public string Adphone { get; set; }
        public string AdEmail { get; set; }
    }
}
